-- TASK 1
-- PART 1. A
CREATE VIEW TASK_1_A AS
    SELECT 
        AGE, DIAGNOSIS_CODE_1 AS DIAGNOSIS_CODE
    FROM
        patient 
    UNION SELECT 
        AGE, DIAGNOSIS_CODE_2 AS DIAGNOSIS_CODE
    FROM
        patient;
        
SET @num:=0, @type:=1;

SELECT 
    R.AGE, R.DISEASE_CODE
FROM
    (SELECT 
        P.AGE, P.DISEASE_CODE, P.COUNT
    FROM
        (SELECT 
        T.AGE,
            T.DISEASE_CODE,
            T.COUNT,
            @NUM:=IF(@TYPE = T.AGE, @NUM + 1, 1) AS ROW_NUMBER,
            @TYPE:=1 AS DUMMY
    FROM
        (SELECT 
        AGE,
            DIAGNOSIS_CODE AS DISEASE_CODE,
            COUNT(DIAGNOSIS_CODE) AS COUNT
    FROM
        TASK_1_A
    GROUP BY AGE , DIAGNOSIS_CODE
    ORDER BY AGE , COUNT(DISEASE_CODE) DESC) T) P
    WHERE
        P.ROW_NUMBER <= 1) R
        INNER JOIN
    (SELECT 
        AGE, COUNT(DIAGNOSIS_CODE) AS TOTAL
    FROM
        TASK_1_A
    GROUP BY AGE) S ON R.AGE = S.AGE;
    
-- PART 1.B
CREATE VIEW TASK_1_B AS
    SELECT 
        AGE, DIAGNOSIS_CODE_1 AS DIAGNOSIS_CODE
    FROM
        patient 
    UNION SELECT 
        AGE, DIAGNOSIS_CODE_2 AS DIAGNOSIS_CODE
    FROM
        patient;

SET @NUM:=0, @TYPE:='';

SELECT 
    R.AGE, R.DISEASE_CODE, R.COUNT / S.TOTAL
FROM
    (SELECT 
        P.AGE, P.DISEASE_CODE, P.COUNT
    FROM
        (SELECT 
        T.AGE,
            T.DISEASE_CODE,
            T.COUNT,
            @NUM:=IF(@TYPE = T.AGE, @NUM + 1, 1) AS ROW_NUMBER,
            @TYPE:=T.AGE AS DUMMY
    FROM
        (SELECT 
        AGE,
            DIAGNOSIS_CODE AS disease_code,
            COUNT(DIAGNOSIS_CODE) AS COUNT
    FROM
        TASK_1_B
    GROUP BY AGE , DIAGNOSIS_CODE
    ORDER BY AGE , COUNT(DISEASE_CODE) DESC) T) P
    WHERE
        P.ROW_NUMBER <= 3) R
        INNER JOIN
    (SELECT 
        AGE, COUNT(DIAGNOSIS_CODE) AS TOTAL
    FROM
        TASK_1_B
    GROUP BY AGE) S ON R.AGE = S.AGE;

-- PART 2.A
SELECT 
    T.SEX, P.DEAD / T.TOTAL
FROM
    (SELECT 
        SEX, COUNT(DISCHARGE_STATUS) AS TOTAL
    FROM
        patient
    GROUP BY SEX) T
        INNER JOIN
    (SELECT 
        SEX, COUNT(DISCHARGE_STATUS) AS DEAD
    FROM
        patient
    WHERE
        DISCHARGE_STATUS = 'B'
    GROUP BY SEX) P ON T.SEX = P.SEX;

-- PART 2.B

-- PART 3.A
SELECT STAY_INDICATOR, COUNT(STAY_INDICATOR) AS DAYS_STAYED
FROM patient
WHERE STAY_INDICATOR = 'S'
GROUP BY STAY_INDICATOR
ORDER BY DAYS_STAYED DESC;

-- PART 3.B
SELECT STAY_INDICATOR, COUNT(STAY_INDICATOR) AS DAYS_STAYED
FROM patient
WHERE STAY_INDICATOR = 'L'
GROUP BY STAY_INDICATOR
ORDER BY DAYS_STAYED DESC;

-- PART 4.A
SELECT LENGTH_OF_STAY, AVG(TOTAL_CHARGES)
FROM patient
GROUP BY LENGTH_OF_STAY;

-- PART 4.B
SELECT 
    T.LENGTH_OF_STAY, P.DEAD / T.TOTAL
FROM
    (SELECT 
        LENGTH_OF_STAY, COUNT(DISCHARGE_STATUS) AS TOTAL
    FROM
        patient
    GROUP BY LENGTH_OF_STAY) T
        LEFT OUTER JOIN
    (SELECT 
        LENGTH_OF_STAY, COUNT(DISCHARGE_STATUS) AS DEAD
    FROM
        patient
    WHERE
        DISCHARGE_STATUS = 'B'
    GROUP BY LENGTH_OF_STAY) P ON T.LENGTH_OF_STAY = P.LENGTH_OF_STAY;
    
-- PART 5
SELECT DISCHARGE_DESTINATION, AGE
FROM patient
GROUP BY DISCHARGE_DESTINATION